# Generated by Django 5.2.1 on 2025-05-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
