# Generated by Django 5.2.1 on 2025-05-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
