# Generated by Django 5.2.1 on 2025-05-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
