# Generated by Django 5.2.1 on 2025-05-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recipes', '0002_delete_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='recipes/')),
                ('description', models.TextField()),
                ('course_name', models.CharField(max_length=200)),
                ('ingredients', models.JSONField()),
                ('instructions', models.JSONField()),
            ],
        ),
    ]
