# Generated by Django 5.2.1 on 2025-05-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0009_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='course_name',
            field=models.CharField(max_length=200),
        ),
    ]
